timeout: '600s'
images: 
  - gcr.io/$PROJECT_ID/inlive-website:$SHORT_SHA
  - gcr.io/$PROJECT_ID/inlive-website:latest
options:
  env:
    - CLOUDSDK_CORE_PROJECT=$PROJECT_ID
    - CLOUD_RUN_PROJECT_NAME=inlive-website
    - _SITE_IMG=gcr.io/$PROJECT_ID/inlive-website:$SHORT_SHA
    - _SITE_IMG_LATEST=gcr.io/$PROJECT_ID/inlive-website:latest
    - _SITE_NAME=inlive-website
steps:
  - id: 'site: image: build'
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: './cloudbuild/cmd.sh'
    args: [site_image_build]
  - id: 'site: cloud_run: deploy'
    name: gcr.io/cloud-builders/gcloud
    entrypoint: './cloudbuild/cmd.sh'
    args: [site_cloud_run_deploy]
    waitFor: ['site: image: build']
