baseURL = '/'
languageCode = 'en-us'
title = 'inLive'
theme = 'inlive'

[params]
  inliveStudioOrigin = 'https://dev-studio.inlive.app'
  inliveAPI = 'https://dev-api.inlive.app'

[caches]
[caches.getjson]
dir = ":cacheDir/:project"
maxAge = "10s"