baseURL = 'https://inlive.app/'
languageCode = 'en-us'
title = 'inLive'
theme = 'inlive'

[security]
  [security.funcs]
    getenv = ['^_HUGO_']

[caches]
[caches.getjson]
dir = ":cacheDir/:project"
maxAge = "10s"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# The below menus don't have actual page
[menu]
  [[menu.docs_sidebar]]
    identifier = "api-references"
    name = "API References"
    weight = 5
    [menu.docs_sidebar.params]
      disabled = true
  [[menu.docs_sidebar]]
    identifier = "stream-api-reference"
    name = "Live Stream API Reference"
    parent = "api-references"
    weight = 1
    url = "https://api.inlive.app/apidocs/index.html"
    [menu.docs_sidebar.params]
      external = true

  [[menu.docs_sidebar]]
    identifier = "hub-api-reference"
    name = "Hub API Reference"
    parent = "api-references"
    weight = 2
    url = "https://hub.inlive.app/apidocs/index.html"
    [menu.docs_sidebar.params]
      external = true