baseURL = 'https://inlive.app/'
languageCode = 'en-us'
title = 'inLive'
theme = 'inlive'

[security]
  [security.funcs]
    getenv = ['^_HUGO_']

[caches]
[caches.getjson]
dir = ":cacheDir/:project"
maxAge = "10s"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
