steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', 
      '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:$BUILD_ID',
      '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME', 
      '--cache-from', 'gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME',
      '.' ]
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$REPO_NAME:$BUILD_ID']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME']
  # Deploy container image to Cloud Run
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
    - run
    - --filename=k8s/development/inlive-website.yaml
    - --location=asia-southeast1
    - --cluster=inlive-dev
    - --output=output/inlive-website
    timeout: 900s
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
    - run
    - --filename=k8s/development/ingress-service.yaml
    - --location=asia-southeast1
    - --cluster=inlive-dev
    - --output=output/ingress-service
    timeout: 900s
images: [
  'gcr.io/$PROJECT_ID/$REPO_NAME:$BUILD_ID',
  'gcr.io/$PROJECT_ID/$REPO_NAME:$BRANCH_NAME',
]
