steps:
  - name: 'node'
    entrypoint: 'npm'
    args: ['install']
  - name: 'node'
    entrypoint: 'npm'
    args: ['install', 'postcss-cli']
  - name: 'gcr.io/$PROJECT_ID/hugo'
  - name: gcr.io/cloud-builders/gsutil
    args: ["-m", "rsync", "-r", "-c", "-d", "./public", "gs://inlive-website-dev"]
images: [
  'gcr.io/${PROJECT_ID}/hugo',
]
tags: ['cloud-builders-community']
