images:
- gcr.io/asgard-livestream/studio-inlive
timeout: '600s'
steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/asgard-livestream/studio-inlive', '-f', 'nginx/nginx.Dockerfile', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/asgard-livestream/studio-inlive']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'inlive-app', '--image', 'gcr.io/asgard-livestream/studio-inlive', '--region', 'asia-southeast2', '--platform', 'managed']
