steps:
# Docker Image used to build hugo site within Cloud Build pipeline.
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/${PROJECT_ID}/hugo', '.']
- name: 'gcr.io/${PROJECT_ID}/hugo'
  args: ['--help']
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/asgard-livestream/inlive-website', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/asgard-livestream/inlive-website']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'inlive-website', '--image', 'gcr.io/asgard-livestream/inlive-website', '--region', 'asia-southeast2', '--platform', 'managed']
timeout: '600s'
images: [
  'gcr.io/asgard-livestream/inlive-website',
  'gcr.io/${PROJECT_ID}/hugo',
]
tags: ['cloud-builders-community']
