apiVersion: apps/v1
kind: Deployment
metadata:
  name: inlive-website
spec:
  replicas: 1
  selector:
    matchLabels:
      run: inlive-website
  template:
    metadata:
      labels:
        run: inlive-website
    spec:
      containers:
      - name: inlive-website-@BRANCH_NAME@
        image: gcr.io/asgard-livestream/inlive-website:@BUILD_ID@
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
        env:
        - name: _HUGO_CLARITY_TRACKING_ID
          value: "DEV_HUGO_CLARITY_TRACKING_ID"
        - name: _HUGO_GOOGLE_ANALYTICS_TRACKING_ID
          value: "DEV_HUGO_GOOGLE_ANALYTICS_TRACKING_ID"
        - name: _HUGO_INLIVE_API_ORIGIN
          value: "DEV_HUGO_INLIVE_API_ORIGIN"
        - name: _HUGO_INLIVE_STUDIO_ORIGIN
          value: "DEV_HUGO_INLIVE_STUDIO_ORIGIN"
---
kind: Service
apiVersion: v1
metadata:
  name: inlive-website-http
spec:
  selector:
    run: inlive-website
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
