name: DeployWeb

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches: [dev]
    # trigger on merge PR
    types:
      - merge

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-deploy:
    # trigger only if the merge was successful, merged_by will be null if PR was closed without merging
    if: github.event.pull_request.merged_by != ''
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: recursive # Fetch the theme
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      # Login to gcloud and export credentials
      - name: Login
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          export_default_credentials: true

      - name: Hugo setup
        uses: peaceiris/actions-hugo@v2.4.13
        with:
          hugo-version: "latest"

      - name: Build
        run: hugo --minify

      - name: Deploy
        run: hugo deploy --target="development"
